version: '3.8'

services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
    networks:
      - portainer_agent_network

networks:
  portainer_agent_network:
    driver: overlay
    attachable: true
